name: Weather Scraper

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:        # manual trigger
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # needed for auto-commit

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install chromedriver-autoinstaller selenium pytz
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Chrome
      run: |
        sudo apt update
        sudo apt install -y wget unzip xvfb libxi6
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
    - name: Run weather scraper
      run: python weather_scraper.py

    - name: Upload CSV artifact
      uses: actions/upload-artifact@v4
      with:
        name: weather-log
        path: weather_log.csv

    - name: Auto-commit updated CSV
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add weather_log.csv
        git commit -m "Update weather_log.csv [auto]" || echo "No changes to commit"
        git push
